language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly
services:
  - mysql
before_script:
  - mysql -e 'create database test charset utf8 collate utf8_general_ci; use test; create table sessions(id int(11) NOT NULL auto_increment, session_id varchar(255), data text, last_access int(11), PRIMARY KEY(id));'
